baseURL = "https://github.com/trevorsmale/cumulus"
weight = 2
title = "Trevor Smale' Notes"
theme = "ace-documentation"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Turn off read more bar 
disableReadmoreNav = true

# Order alphabetically
orderSectionby = "title"

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
